import { useState, useEffect } from 'react';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { AlertCircle, Plus, Trash2 } from 'lucide-react';
import type { Document } from '../../../shared/schemas';

interface KeyValuePair {
  key: string;
  value: string;
}

// Note: Embeddings are auto-generated by ChromaDB when adding/updating documents
// and are not exposed in the form. They are lazy-loaded in DocumentDetail view.

interface DocumentEditorProps {
  document?: Document | null;
  onDataChange?: (data: DocumentFormData) => void;
}

export interface DocumentFormData {
  id: string;
  document: string;
  metadata: string; // JSON string
  autoGenerateId: boolean;
}

/**
 * DocumentEditor component - form for creating/editing documents
 *
 * Features:
 * - Document ID (with auto-generate option)
 * - Document text (large textarea)
 * - Metadata (JSON editor with validation)
 * - Real-time validation
 * - Character count
 *
 * Note: Embeddings are auto-generated by ChromaDB and not editable via this form.
 */
// Helper to convert metadata object to key-value pairs
const metadataToKeyValuePairs = (metadata: Record<string, unknown> | null): KeyValuePair[] => {
  if (!metadata || Object.keys(metadata).length === 0) {
    return [{ key: '', value: '' }]; // Start with one empty pair
  }
  return Object.entries(metadata).map(([key, value]) => ({
    key,
    value: typeof value === 'string' ? value : JSON.stringify(value),
  }));
};

// Helper to convert key-value pairs to JSON string
const keyValuePairsToJson = (pairs: KeyValuePair[]): string => {
  const validPairs = pairs.filter((p) => p.key.trim() !== '');
  if (validPairs.length === 0) return '{}';

  const obj: Record<string, string | number | boolean> = {};
  validPairs.forEach((pair) => {
    // Try to parse value as JSON for numbers/booleans
    try {
      const parsed = JSON.parse(pair.value);
      if (typeof parsed === 'number' || typeof parsed === 'boolean') {
        obj[pair.key] = parsed;
      } else {
        obj[pair.key] = pair.value;
      }
    } catch {
      obj[pair.key] = pair.value;
    }
  });
  return JSON.stringify(obj, null, 2);
};

// Helper to parse JSON string to key-value pairs
const jsonToKeyValuePairs = (json: string): KeyValuePair[] | null => {
  try {
    const parsed = JSON.parse(json);
    if (typeof parsed !== 'object' || Array.isArray(parsed)) return null;
    const entries = Object.entries(parsed);
    if (entries.length === 0) return [{ key: '', value: '' }];
    return entries.map(([key, value]) => ({
      key,
      value: typeof value === 'string' ? value : JSON.stringify(value),
    }));
  } catch {
    return null;
  }
};

export function DocumentEditor({ document, onDataChange }: DocumentEditorProps) {
  const initialMetadata = document?.metadata
    ? JSON.stringify(document.metadata, null, 2)
    : '{}';

  const [formData, setFormData] = useState<DocumentFormData>({
    id: document?.id || '',
    document: document?.document || '',
    metadata: initialMetadata,
    autoGenerateId: !document?.id,
  });

  const [keyValuePairs, setKeyValuePairs] = useState<KeyValuePair[]>(
    metadataToKeyValuePairs(document?.metadata as Record<string, unknown> | null)
  );
  const [metadataMode, setMetadataMode] = useState<'keyvalue' | 'json'>('keyvalue');

  const [errors, setErrors] = useState<{
    metadata?: string;
    document?: string;
  }>({});

  // Validate JSON fields - metadata is now mandatory
  const validateMetadata = (value: string): boolean => {
    if (!value.trim() || value.trim() === '{}') {
      setErrors((prev) => ({
        ...prev,
        metadata: 'At least one metadata key-value pair is required',
      }));
      return false;
    }

    try {
      const parsed = JSON.parse(value);
      if (typeof parsed !== 'object' || Array.isArray(parsed)) {
        setErrors((prev) => ({ ...prev, metadata: 'Metadata must be a JSON object' }));
        return false;
      }
      if (Object.keys(parsed).length === 0) {
        setErrors((prev) => ({
          ...prev,
          metadata: 'At least one metadata key-value pair is required',
        }));
        return false;
      }
      setErrors((prev) => ({ ...prev, metadata: undefined }));
      return true;
    } catch {
      setErrors((prev) => ({ ...prev, metadata: 'Invalid JSON format' }));
      return false;
    }
  };

  // Validate key-value pairs
  const validateKeyValuePairs = (pairs: KeyValuePair[]): boolean => {
    const validPairs = pairs.filter((p) => p.key.trim() !== '');
    if (validPairs.length === 0) {
      setErrors((prev) => ({
        ...prev,
        metadata: 'At least one metadata key-value pair is required',
      }));
      return false;
    }
    // Check for duplicate keys
    const keys = validPairs.map((p) => p.key.trim());
    const uniqueKeys = new Set(keys);
    if (keys.length !== uniqueKeys.size) {
      setErrors((prev) => ({ ...prev, metadata: 'Duplicate keys are not allowed' }));
      return false;
    }
    setErrors((prev) => ({ ...prev, metadata: undefined }));
    return true;
  };

  const validateDocument = (value: string): boolean => {
    if (!value.trim()) {
      setErrors((prev) => ({ ...prev, document: 'Document text is required' }));
      return false;
    }
    setErrors((prev) => ({ ...prev, document: undefined }));
    return true;
  };

  // Update form data and notify parent
  const updateFormData = (updates: Partial<DocumentFormData>) => {
    const newData = { ...formData, ...updates };
    setFormData(newData);
    if (onDataChange) {
      onDataChange(newData);
    }
  };

  // Key-value pair management functions
  const addKeyValuePair = () => {
    setKeyValuePairs([...keyValuePairs, { key: '', value: '' }]);
  };

  const removeKeyValuePair = (index: number) => {
    if (keyValuePairs.length > 1) {
      const newPairs = keyValuePairs.filter((_, i) => i !== index);
      setKeyValuePairs(newPairs);
      const json = keyValuePairsToJson(newPairs);
      updateFormData({ metadata: json });
    }
  };

  const updateKeyValuePair = (index: number, field: 'key' | 'value', newValue: string) => {
    const newPairs = keyValuePairs.map((pair, i) =>
      i === index ? { ...pair, [field]: newValue } : pair
    );
    setKeyValuePairs(newPairs);
    const json = keyValuePairsToJson(newPairs);
    updateFormData({ metadata: json });
  };

  // Handle tab change - sync data between modes
  const handleTabChange = (value: string) => {
    const newMode = value as 'keyvalue' | 'json';

    if (newMode === 'keyvalue') {
      // Switching to key-value mode - parse JSON to pairs
      const pairs = jsonToKeyValuePairs(formData.metadata);
      if (pairs) {
        setKeyValuePairs(pairs);
      }
    } else {
      // Switching to JSON mode - already synced via updateFormData
    }

    setMetadataMode(newMode);
  };

  // Validate on change
  useEffect(() => {
    if (metadataMode === 'keyvalue') {
      validateKeyValuePairs(keyValuePairs);
    } else {
      validateMetadata(formData.metadata);
    }
    validateDocument(formData.document);
  }, [formData.metadata, formData.document, keyValuePairs, metadataMode]);

  return (
    <div className="space-y-6">
      {/* Document ID */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label htmlFor="doc-id">Document ID</Label>
          <div className="flex items-center space-x-2">
            <Checkbox
              id="auto-id"
              checked={formData.autoGenerateId}
              onCheckedChange={(checked) =>
                updateFormData({ autoGenerateId: checked as boolean })
              }
              disabled={!!document} // Can't change for existing documents
            />
            <label
              htmlFor="auto-id"
              className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              Auto-generate
            </label>
          </div>
        </div>
        <Input
          id="doc-id"
          value={formData.id}
          onChange={(e) => updateFormData({ id: e.target.value })}
          disabled={formData.autoGenerateId || !!document}
          placeholder="Leave empty to auto-generate"
          className="font-mono text-sm"
        />
        {document && (
          <p className="text-xs text-muted-foreground">
            Document ID cannot be changed for existing documents
          </p>
        )}
      </div>

      {/* Document Text */}
      <div className="space-y-2">
        <Label htmlFor="doc-text">
          Document Text <span className="text-destructive">*</span>
        </Label>
        <Textarea
          id="doc-text"
          value={formData.document}
          onChange={(e) => updateFormData({ document: e.target.value })}
          rows={10}
          className="resize-none font-mono text-sm"
          placeholder="Enter document text..."
        />
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>{formData.document.length} characters</span>
          {errors.document && (
            <span className="text-destructive">{errors.document}</span>
          )}
        </div>
      </div>

      {/* Metadata */}
      <div className="space-y-2">
        <Label>
          Metadata <span className="text-destructive">*</span>
        </Label>
        <Tabs value={metadataMode} onValueChange={handleTabChange}>
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="keyvalue">Key-Value</TabsTrigger>
            <TabsTrigger value="json">JSON</TabsTrigger>
          </TabsList>

          {/* Key-Value Mode */}
          <TabsContent value="keyvalue" className="space-y-3">
            <div className="space-y-2">
              {keyValuePairs.map((pair, index) => (
                <div key={index} className="flex items-center gap-2">
                  <Input
                    placeholder="Key"
                    value={pair.key}
                    onChange={(e) => updateKeyValuePair(index, 'key', e.target.value)}
                    className="flex-1 font-mono text-sm"
                  />
                  <Input
                    placeholder="Value"
                    value={pair.value}
                    onChange={(e) => updateKeyValuePair(index, 'value', e.target.value)}
                    className="flex-1 font-mono text-sm"
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    onClick={() => removeKeyValuePair(index)}
                    disabled={keyValuePairs.length === 1}
                    className="shrink-0"
                  >
                    <Trash2 className="h-4 w-4 text-muted-foreground hover:text-destructive" />
                  </Button>
                </div>
              ))}
            </div>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={addKeyValuePair}
              className="w-full"
            >
              <Plus className="mr-2 h-4 w-4" />
              Add Field
            </Button>
            <p className="text-xs text-muted-foreground">
              At least one key-value pair is required. Values are stored as strings unless
              they are valid numbers or booleans.
            </p>
          </TabsContent>

          {/* JSON Mode */}
          <TabsContent value="json" className="space-y-2">
            <Textarea
              id="doc-metadata"
              value={formData.metadata}
              onChange={(e) => updateFormData({ metadata: e.target.value })}
              rows={5}
              className={`resize-none font-mono text-xs ${errors.metadata ? 'border-destructive' : ''}`}
              placeholder='{"key": "value", "author": "John Doe"}'
            />
            <p className="text-xs text-muted-foreground">
              Enter metadata as a JSON object. At least one key-value pair is required.
            </p>
          </TabsContent>
        </Tabs>

        {errors.metadata && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{errors.metadata}</AlertDescription>
          </Alert>
        )}
      </div>

    </div>
  );
}

/**
 * Validate form data before submission
 */
export function validateDocumentForm(data: DocumentFormData): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  // Validate document text
  if (!data.document.trim()) {
    errors.push('Document text is required');
  }

  // Validate metadata JSON - now mandatory
  if (!data.metadata.trim() || data.metadata.trim() === '{}') {
    errors.push('At least one metadata key-value pair is required');
  } else {
    try {
      const parsed = JSON.parse(data.metadata);
      if (typeof parsed !== 'object' || Array.isArray(parsed)) {
        errors.push('Metadata must be a JSON object');
      } else if (Object.keys(parsed).length === 0) {
        errors.push('At least one metadata key-value pair is required');
      }
    } catch {
      errors.push('Invalid metadata JSON format');
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
