import { useState, useEffect } from 'react';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { AlertCircle } from 'lucide-react';
import type { Document } from '../../../shared/schemas';

// Note: Embeddings are auto-generated by ChromaDB when adding/updating documents
// and are not exposed in the form. They are lazy-loaded in DocumentDetail view.

interface DocumentEditorProps {
  document?: Document | null;
  onDataChange?: (data: DocumentFormData) => void;
}

export interface DocumentFormData {
  id: string;
  document: string;
  metadata: string; // JSON string
  autoGenerateId: boolean;
}

/**
 * DocumentEditor component - form for creating/editing documents
 *
 * Features:
 * - Document ID (with auto-generate option)
 * - Document text (large textarea)
 * - Metadata (JSON editor with validation)
 * - Real-time validation
 * - Character count
 *
 * Note: Embeddings are auto-generated by ChromaDB and not editable via this form.
 */
export function DocumentEditor({ document, onDataChange }: DocumentEditorProps) {
  const [formData, setFormData] = useState<DocumentFormData>({
    id: document?.id || '',
    document: document?.document || '',
    metadata: document?.metadata ? JSON.stringify(document.metadata, null, 2) : '{}',
    autoGenerateId: !document?.id,
  });

  const [errors, setErrors] = useState<{
    metadata?: string;
    document?: string;
  }>({});

  // Validate JSON fields
  const validateMetadata = (value: string): boolean => {
    if (!value.trim()) {
      setErrors((prev) => ({ ...prev, metadata: undefined }));
      return true;
    }

    try {
      const parsed = JSON.parse(value);
      if (typeof parsed !== 'object' || Array.isArray(parsed)) {
        setErrors((prev) => ({ ...prev, metadata: 'Metadata must be a JSON object' }));
        return false;
      }
      setErrors((prev) => ({ ...prev, metadata: undefined }));
      return true;
    } catch (error) {
      setErrors((prev) => ({ ...prev, metadata: 'Invalid JSON format' }));
      return false;
    }
  };

  const validateDocument = (value: string): boolean => {
    if (!value.trim()) {
      setErrors((prev) => ({ ...prev, document: 'Document text is required' }));
      return false;
    }
    setErrors((prev) => ({ ...prev, document: undefined }));
    return true;
  };

  // Update form data and notify parent
  const updateFormData = (updates: Partial<DocumentFormData>) => {
    const newData = { ...formData, ...updates };
    setFormData(newData);
    if (onDataChange) {
      onDataChange(newData);
    }
  };

  // Validate on change
  useEffect(() => {
    validateMetadata(formData.metadata);
    validateDocument(formData.document);
  }, [formData.metadata, formData.document]);

  return (
    <div className="space-y-6">
      {/* Document ID */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label htmlFor="doc-id">Document ID</Label>
          <div className="flex items-center space-x-2">
            <Checkbox
              id="auto-id"
              checked={formData.autoGenerateId}
              onCheckedChange={(checked) =>
                updateFormData({ autoGenerateId: checked as boolean })
              }
              disabled={!!document} // Can't change for existing documents
            />
            <label
              htmlFor="auto-id"
              className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              Auto-generate
            </label>
          </div>
        </div>
        <Input
          id="doc-id"
          value={formData.id}
          onChange={(e) => updateFormData({ id: e.target.value })}
          disabled={formData.autoGenerateId || !!document}
          placeholder="Leave empty to auto-generate"
          className="font-mono text-sm"
        />
        {document && (
          <p className="text-xs text-muted-foreground">
            Document ID cannot be changed for existing documents
          </p>
        )}
      </div>

      {/* Document Text */}
      <div className="space-y-2">
        <Label htmlFor="doc-text">
          Document Text <span className="text-destructive">*</span>
        </Label>
        <Textarea
          id="doc-text"
          value={formData.document}
          onChange={(e) => updateFormData({ document: e.target.value })}
          rows={10}
          className="resize-none font-mono text-sm"
          placeholder="Enter document text..."
        />
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>{formData.document.length} characters</span>
          {errors.document && (
            <span className="text-destructive">{errors.document}</span>
          )}
        </div>
      </div>

      {/* Metadata */}
      <div className="space-y-2">
        <Label htmlFor="doc-metadata">Metadata (JSON Object)</Label>
        <Textarea
          id="doc-metadata"
          value={formData.metadata}
          onChange={(e) => updateFormData({ metadata: e.target.value })}
          rows={5}
          className={`resize-none font-mono text-xs ${errors.metadata ? 'border-destructive' : ''}`}
          placeholder='{"key": "value", "author": "John Doe"}'
        />
        {errors.metadata && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{errors.metadata}</AlertDescription>
          </Alert>
        )}
        <p className="text-xs text-muted-foreground">
          Optional: Enter metadata as a JSON object
        </p>
      </div>

    </div>
  );
}

/**
 * Validate form data before submission
 */
export function validateDocumentForm(data: DocumentFormData): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  // Validate document text
  if (!data.document.trim()) {
    errors.push('Document text is required');
  }

  // Validate metadata JSON
  if (data.metadata.trim()) {
    try {
      const parsed = JSON.parse(data.metadata);
      if (typeof parsed !== 'object' || Array.isArray(parsed)) {
        errors.push('Metadata must be a JSON object');
      }
    } catch (error) {
      errors.push('Invalid metadata JSON format');
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
